server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:sqlserver://sqlserver:1433;databaseName=csms_auth;encrypt=false;trustServerCertificate=true
    username: sa
    password: Password123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
